### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/microsoft-teams#1]
- [x] Code Review
- [x] Add to website
- [x] Create packagist package
- [x] Github actions
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by atymic** [comment]
Ready to tag the first release when you're ready :)

**Comment by Tob0t** [comment]
Done, looks good :)
One more thing: The link in the badges to travis leads to https://travis-ci.org/github/laravel-notification-channels/microsoft-teams which is not found, maybe you can fix that?

**Comment by atymic** [comment]
Prefect. Will switch the repo to GH actions shortly :)

**Comment by atymic** [comment]
On website 👍 
https://github.com/laravel-notification-channels/website/pull/26

Channel live :) Closing this
