### ISSUE TITLE
[Feature] Dismiss Button

### ISSUE THREAD

**Issue by hanstsangcwc** [laravel-notification-channels/microsoft-teams#10]
is it possible to make a button disappear after clicking it?

or dismiss the whole card like polly?

Thank you

![image](https://user-images.githubusercontent.com/50945933/100962300-06f7cb00-355f-11eb-9b42-cac9637a3866.png)

**Comment by Tob0t** [comment]
Hmm I never tried it but I suggest to check out https://messagecardplayground.azurewebsites.net/ or https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#actions

Basically you should be able to create everything described in the documentation with the method `action(string $text, $type = 'OpenUri', array $params = [])`

**Comment by Tob0t** [comment]
*Closed due to inactivity*
