### ISSUE TITLE
Notification driver is registered as 'teams' however, routeNotificationFor is being passed 'microsoftTeams'

### ISSUE THREAD

**Issue by tdondich** [laravel-notification-channels/microsoft-teams#12]
There is inconsistency in the naming.  This should be consistent as either teams or microsoftTeams.  For compatibility, registering as both might make sense along with a deprecation notice for whichever you remove in the future?

**Comment by Tob0t** [comment]
Thats true, I first just called it teams and then refactored it to microsoftTeams. Seems like I forgot it in `MicrosoftTeamsServiceProvider.php`. Did you see the inconsistency anywhere else?

**Comment by tdondich** [comment]
Not off hand.  I didn't go through the entire codebase though.  I think that's really the major spot.
