### ISSUE TITLE
On Demand

### ISSUE THREAD

**Issue by nam-co** [laravel-notification-channels/microsoft-teams#17]
Hi,  thanks for the work on the package, is there a way to. use this package with on demand? https://laravel.com/docs/8.x/notifications#on-demand-notifications

Also, Can I use this:
   ```
 public function via($notifiable)
    {
        return ['mail','slack','teams'];
    }
```

Appreciate any help,  thanks

**Comment by jmurphy45** [comment]
Any updates on this I am trying to do the same and have no luck.

**Comment by atymic** [comment]
Yep, should just be able to do `Notification::route('teams', 'http://blah.com')`?

**Comment by Tob0t** [comment]
Yes as @atymic said you can use it like this:
```
Notification::route('teams', $webhookURL)->notify(new SubscriptionCreated());
```
or you specifiy it in the Notification itself and leave it blank:
```
Notification::route('teams', '')->notify(new SubscriptionCreated());
```
```
class SubscriptionCreated extends Notification
...
public function toMicrosoftTeams($notifiable)
    {
        return MicrosoftTeamsMessage::create()
            ->to(config('services.teams.sales_url'))
            ->type('success')
            ->title('Subscription Created')
            ->content('Yey, you got a **new subscription**. Maybe you want to contact him if he needs any support?')
            ->button('Check User', 'https://foo.bar/users/123');
    }
```

Regarding your second question:
You can use for sure this (not sure if its working with the string alias as well):
```
public function via($notifiable)
{
    return [MicrosoftTeamsChannel::class];
}
```
