### ISSUE TITLE
help to sending message

### ISSUE THREAD

**Issue by neowolfman** [laravel-notification-channels/microsoft-teams#23]
Hello, I would like to send an online message after a task, is it possible? Could you give me an example?

Note: I have not been able to send without creating a Controller, that's why my query.

Thank you

Example code

        $channel = new MicrosoftTeamsChannel(config('services.microsoft_teams.DTES_url'));

        $teamsMessage= MicrosoftTeamsMessage::create()
            ->type('warning')
            ->title('Cliente No Encontrado')
            ->content('Test<br><br>');

        $response = $channel->send(null, **$teamsMessage);**

**Comment by Tob0t** [comment]
Please check out the [readme ](https://github.com/laravel-notification-channels/microsoft-teams/blob/master/README.md)for an example or the [laravel documentation](https://laravel.com/docs/9.x/notifications) how to send a notification.
