### ISSUE TITLE
Timeout for requests

### ISSUE THREAD

**Issue by Antobai** [laravel-notification-channels/microsoft-teams#26]
Hi,

thanks for your great package, it has worked flawlessly for 2 years in my company.

But I think it would be great to add a timeout option for requests, something in config files which would be 0 by default but can be configured for a timeout.

Context :
There were some problems with incoming teams webhooks this monday and tuesday (with absolutely no communication from microsoft about the issue by the way) which resulted in a disruption of our ticketing system (which sends notifcations to teams) at my company.

random 500 and 503 errors which we can catch and log, without any disruption of service, but the webhook would sometimes not respond at all, which resulted in a 504 error for our customers.

I had to fork the project in a private package and add this functionnality, since this was critical for us and I could'nt wait for an approval of a PR, but let me know if you're interested so I can make it a little cleaner and propose a PR.

**Comment by Tob0t** [comment]
Hi @Antobai,
thanks for the info and the idea of a timeout.
I think that would be a valuable feature. Feel free to create a PR, then I will review it :)

**Comment by Tob0t** [comment]
Closed due to inactivity
